[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bbb_render"
version = "0.0.1"
authors = [
  { name="James Henstridge", email="james@jamesh.id.au" },
  { name=" Valerio Bozzolan,", email="nsa+gitspam@succhia.cz" },
  { name="Camille Lafitte", email="cam.lafit@azerttyu.net" },

]
description = "BigBlueButton Presentation Renderer"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.scripts]
download = "bbb_render.download:main"
make-xges = "bbb_render.make_xges:main"

[project.urls]
Homepage = "https://public.git.webelys.com/BigBlueButton/bbb-render"
Issues = "https://public.git.webelys.com/BigBlueButton/bbb-render/issues"
